routes/web.php
<?php

use App\Http\Controllers\Main\HomeController;
use App\Http\Controllers\Main\PlayerController;
use App\Http\Controllers\Main\PlayerStatsController;
use App\Http\Controllers\Main\StandingController;
use App\Http\Controllers\Admin\LastMatchController;
use App\Http\Controllers\Admin\UpcomingMatchController;
use App\Http\Controllers\Main\TimetableController;
use App\Http\Controllers\Admin\PlayerController as AdminPlayerController;
use App\Http\Controllers\Admin\StandingController as AdminStandingController;
use App\Http\Controllers\Admin\TimetableController as AdminTimetableController;
use App\Http\Controllers\PageController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UploadController;
use App\Http\Controllers\Main\GalleryController;
use App\Http\Controllers\Admin\GalleryController as AdminGalleryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([], function () {
    Route::get('/', [HomeController::class, 'index'])
        ->name('index');

    Route::get('/gallery', GalleryController::class)
        ->name('gallery');

    Route::group([
        'prefix' => '/season/',
        'as' => 'season.'
    ], function () {
        Route::get('/timetable', [TimetableController::class, 'index'])
            ->name('timetable.index');

        Route::get('/standings', [StandingController::class, 'index'])
            ->name('standings.index');

        Route::get('/players/stats', [PlayerStatsController::class, 'index'])
            ->name('stats.index');

        Route::resource('players', PlayerController::class)
            ->only(['index', 'show'])
            ->where(['player', '[0-9]+']);
    });

    /* AUTH FOR ADMIN ROUTES */
    Route::middleware(['auth'])->group(function () {
        /* ADMIN ROUTES */
        Route::group([
            'prefix' => '/admin',
            'as' => 'admin.'
        ], function () {
            /* DASHBOARD */
            Route::get('/', function () {
                return view('admin.dashboard');
            })->name('dashboard');

            Route::post('/upload', [UploadController::class, 'store']);

            /* TIMETABLE */
            Route::get('/timetable/create', [AdminTimetableController::class, 'create'])
                ->name('timetable.create');

            Route::post('/timetable', [AdminTimetableController::class, 'store'])
                ->name('timetable.store');

            Route::get('/timetable/edit', [AdminTimetableController::class, 'edit'])
                ->name('timetable.edit');

            Route::delete('/timetable', [AdminTimetableController::class, 'destroy'])
                ->name('timetable.destroy');

            Route::delete('/timetable/one/', [AdminTimetableController::class, 'destroyOne'])
                ->name('timetable.destroy.one');


            /* STANDING */
            Route::get('/standing/create', [AdminStandingController::class, 'create'])
                ->name('standing.create');

            Route::post('/standing', [AdminStandingController::class, 'store'])
                ->name('standing.store');

            Route::delete('/standing', [AdminStandingController::class, 'destroy'])
                ->name('standing.destroy');

            /* MATCHES */
            Route::group([
                'prefix' => '/matches/',
                'as' => 'matches.'
            ], function () {
                Route::get('/last/edit', [LastMatchController::class, 'edit'])
                    ->name('last.edit');

                Route::put('/last', [LastMatchController::class, 'update'])
                    ->name('last.update');

                Route::get('/upcoming/edit', [UpcomingMatchController::class, 'edit'])
                    ->name('upcoming.edit');

                Route::put('/upcoming', [UpcomingMatchController::class, 'update'])
                    ->name('upcoming.update');
            });

            /* PLAYERS */
            Route::resource('players', AdminPlayerController::class)
                ->only('index', 'store', 'update', 'edit', 'destroy')
                ->where(['player', '[0-9]+']);

            Route::group([
                'prefix' => '/players',
                'as' => 'players.'
            ], function () {
                Route::put('/{player}/restore', [AdminPlayerController::class, 'restoreDefaults'])
                    ->name('restore')
                    ->where('player', '[0-9]+');

                Route::put('/', [AdminPlayerController::class, 'updatePlayedMatches'])
                    ->name('update.playedMatches');

                Route::delete('/image/{player}', [AdminPlayerController::class, 'destroyImage'])
                    ->name('destroy.image')
                    ->where('player', '[0-9]+');
            });

            /* GALLERY */
            Route::group([
                'prefix' => '/photos',
                'as' => 'photos.'
            ], function () {
                Route::get('/create', [AdminGalleryController::class, 'create'])
                    ->name('create');
                Route::post('/', [AdminGalleryController::class, 'store'])
                    ->name('store');
                Route::delete('/{photo}', [AdminGalleryController::class, 'destroy'])
                    ->name('destroy');
            });
        });
    });

    /* STATIC PAGES */
    Route::get('/{page}', PageController::class)
        ->name('page')
        ->where('page', 'about|contact|privacy-policy');
});

/* AUTH */
Auth::routes();

Auth::routes([
     'register' => false,   // disable registration for new users
     'reset' => false,  // disable password reset
     'verify' => false, // disable email verification
]);

resources/views/admin/dashboard.blade.php
@extends('layout.app')

@section('content')
    <x-admin-pages-template title="Dashboard" cardHeader="Strona główna">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <div class="row mt-3">
                        <div class="col-12">
                            <h4>Witaj <b>{{ Auth::user()->name ?? '' }}</b></h4>
                        </div>
                    </div>
                    <hr>
                    <div class="row mt-4">
                        <div class="col-12">
                            <img src="{{ url('/assets/admin_panel.png') }}"
                                 alt="Panel administratora" width="30%">
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-12">
                            <p>Ostatnie logowanie:
                                <strong>{{ Auth::user()->last_login_at ?? '' }}</strong></p>
                            @can('admin-level')
                                <p>IP:<strong>{{ Auth::user()->last_login_ip ?? '' }}</strong></p>
                            @endcan
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </x-admin-pages-template>
@endsection

resources/views/admin/photos.blade.php
@extends('layout.app')

@section('content')
    <div class="d-flex" id="wrapper">
    @include('shared.sidebar-admin')
    <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <i class="fas fa-bars toggle-admin-icon" id="menu-toggle"></i>
            </nav>
            @include('shared.messages')
            <div class="container-fluid mb-5">
                <div class="row mt-5">
                    <div class="col-1 col-lg-2"></div>
                    <div class="col-10 col-lg-8 bg-white shadow-lg text-center">
                        <h2 class="text-uppercase font-weight-bold mt-3">Galeria</h2>
                        <hr>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-outline-success" data-toggle="modal"
                                data-target="#staticBackdropAdd">
                            Dodaj nowe zdjęcie
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="staticBackdropAdd" data-backdrop="static" data-keyboard="false"
                             tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="staticBackdropLabel">Dodaj zdjęcie</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{{ route('admin.photos.store') }}" method="POST"
                                              enctype="multipart/form-data">
                                            @csrf
                                            <div class="custom-file">
                                                <input type="file" name="image"
                                                       class="custom-file-input @error('image') is-invalid @enderror"
                                                       id="image" accept="image/*">
                                                <label class="custom-file-label text-left" for="image"
                                                       data-browse="Przeglądaj">Wybierz zdjęcie...</label>
                                                @error('image')
                                                <div class="alert alert-danger d-block">{{ $message }}</div>
                                                @enderror
                                            </div>
                                            <div class="form-group mt-2">
                                                <label for="description">Opis (opcjonalny)</label>
                                                <textarea name="description" class="form-control" id="description" rows="3"></textarea>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-outline-secondary"
                                                        data-dismiss="modal">Zamknij
                                                </button>
                                                <button type="submit" class="btn btn-outline-success">Dodaj</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card border-success m-4">
                            <h5 class="card-header">Lista zdjęć</h5>
                            <div class="card-body">
                                <div class="row">

                                    {{--                                one card with photo--}}
                                    @foreach ($photos as $photo)
                                        <div
                                            class="col-6 col-xl-3 mb-3 d-flex align-items-stretch justify-content-center">
                                            <div class="card" style="width: 14rem;">
                                                <div class="imageGallery1">
                                                    <a href="{{ asset('storage/' . $photo->path) }}"><img
                                                            src="{{ asset('storage/' . $photo->path) }}"
                                                            class="card-img-top" alt="Zdjęcie"/></a>
                                                </div>
                                                <div class="card-body d-flex align-items-end justify-content-center">
                                                    <div>
                                                        <span class="d-flex justify-content-center">Utworzono:</span>
                                                        <span
                                                            class="d-flex justify-content-center mb-2">{{ $photo->created_at }}</span>

                                                        <!-- Button trigger modal -->
                                                        <button type="button" class="btn btn-outline-danger btn-sm"
                                                                data-toggle="modal" data-target="#staticBackdropDelete">
                                                            Usuń
                                                        </button>

                                                        <!-- Modal -->
                                                        <div class="modal fade" id="staticBackdropDelete"
                                                             data-backdrop="static" data-keyboard="false" tabindex="-1"
                                                             aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                                            <div class="modal-dialog modal-dialog-centered">
                                                                <div class="modal-content">
                                                                    <div class="modal-header">
                                                                        <h5 class="modal-title"
                                                                            id="staticBackdropLabel">Potwierdzenie
                                                                            usunięcia zdjęcia</h5>
                                                                        <button type="button" class="close"
                                                                                data-dismiss="modal" aria-label="Close">
                                                                            <span aria-hidden="true">&times;</span>
                                                                        </button>
                                                                    </div>
                                                                    <div class="modal-body">
                                                                        <p>Czy na pewno chcesz usunąć to zdjęcie?</p>
                                                                        <form
                                                                            action="{{ route('admin.photos.destroy', ['photo' => $photo->id]) }}"
                                                                            method="POST">
                                                                            @csrf
                                                                            @method('DELETE')
                                                                            <div class="modal-footer">
                                                                                <button type="button"
                                                                                        class="btn btn-outline-secondary"
                                                                                        data-dismiss="modal">Zamknij
                                                                                </button>
                                                                                <button type="submit"
                                                                                        class="btn btn-outline-danger">
                                                                                    Usuń
                                                                                </button>
                                                                            </div>
                                                                        </form>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                                @if ($photos->total() !== 0)
                                    <div class="row">
                                        @if ($photos->total() >= $photos->perPage())
                                            <div class="col-12 col-lg-2 text-center pt-3">
                                                {{ $photos->appends(request()->query())->links() }}
                                            </div>
                                        @endif
                                        <div class="col-12 col-lg-10 text-left d-flex align-items-center">
                                            <span>Wyświetlono {{ ($photos->currentPage() - 1) * $photos->perPage() + 1 }} - @if ($photos->currentPage() === $photos->lastPage()) {{ $photos->total() }} @else {{ $photos->currentPage() * $photos->perPage() }} @endif z {{ $photos->total() }}</span>
                                        </div>
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="col-1 col-lg-2"></div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->
@endsection

resources/views/admin/players.blade.php
@extends('layout.app')

@section('content')
    <div class="d-flex" id="wrapper">
    @include('shared.sidebar-admin')
    <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <i class="fas fa-bars toggle-admin-icon" id="menu-toggle"></i>
            </nav>
            @include('shared.messages')
            @error('played_matches')
            <div class="alert alert-danger m-3">{{ $message }}</div>
            @enderror
            <div class="container-fluid">
                <div class="row mt-5 mb-5">
                    <div class="col-1 col-lg-2"></div>
                    <div class="col-10 col-xl-8 bg-white shadow-lg text-center">
                        <h2 class="text-uppercase font-weight-bold mt-3">Lista zawodników</h2>
                        <hr>
                        <table class="table table-sm table-responsive-lg table-striped table-bordered mt-4 table-font">
                            <thead class="thead-dark">
                            <tr>
                                <th class="text-center align-middle">Lp.</th>
                                <th class="text-center align-middle">Nr</th>
                                <th class="text-center align-middle">
                                    Nazwisko
                                    @sortablelink('last_name' , '')
                                </th>
                                <th class="text-center align-middle">
                                    Imię
                                    @sortablelink('first_name' , '')
                                </th>
                                <th class="text-center align-middle">
                                    Pozycja
                                    @sortablelink('position' , '')
                                </th>
                                <th class="text-center align-middle">
                                    Rozegrane mecze
                                    @sortablelink('played_matches' , '')
                                </th>
                                <th class="text-center align-middle">Opcje</th>
                                <th class="text-center align-middle">
                                    Ostatnia aktualizacja
                                    @sortablelink('updated_at' , '')
                                </th>
                            </tr>
                            </thead>
                            <tbody class="table-light">
                            @foreach($players ?? [] as $player)
                                <tr>
                                    <td class="text-center align-middle">{{ ($players->currentpage() - 1) * $players->perpage() + $loop->index + 1 }}</td>
                                    <td class="text-center align-middle">{{ $player->nr }}</td>
                                    <td class="text-center align-middle text-uppercase">{{ $player->last_name }}</td>
                                    <td class="text-center align-middle">{{ $player->first_name }}</td>
                                    <td class="text-center align-middle">{{ $player->position }}</td>
                                    <td class="text-center align-middle">
                                        <form action="{{ 
                                          route('admin.players.update.playedMatches', 
                                          [
                                            'sort' => request()->query('sort') ?? '',
                                            'direction' => request()->query('direction') ?? '',
                                            'page' => request()->query('page') ?? '',
                                          ]) 
                                          }}" 
                                          method="POST">
                                            @csrf
                                            @method('PUT')
                                            <div class="form-row">
                                                <div class="col-12 col-xl-8">
                                                    <input type="number" name="played_matches"
                                                          value="{{ $player->played_matches ?? 0 }}"
                                                          class="form-control" placeholder="0" min="0" step="1"
                                                          required>
                                                    <input type="hidden" name="playerId" value="{{ $player->id }}">
                                                </div>
                                                <div class="col-12 col-xl-4 mt-2 m-xl-0">
                                                    <button type="submit" class="btn btn-outline-success">Zapisz
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                    </td>
                                    <td class="text-center align-middle">
                                        <a href="{{ route('admin.players.edit', ['player' => $player->id]) }}"
                                          class="btn btn-outline-info">Szczegóły</a>
                                    </td>
                                    <td class="text-center align-middle">{{ \Carbon\Carbon::parse($player->updated_at)->diffForHumans() }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        @if ($players->total() !== 0)
                            <div class="row">
                                @if ($players->total() >= $players->perPage())
                                    <div class="col-12 col-lg-2 text-center pt-3">
                                        {{ $players->appends(request()->query())->links() }}
                                    </div>
                                @endif
                                <div class="col-12 col-lg-10 text-left d-flex align-items-center">
                                    <span>Wyświetlono {{ ($players->currentPage() - 1) * $players->perPage() + 1 }} - @if ($players->currentPage() === $players->lastPage()) {{ $players->total() }} @else {{ $players->currentPage() * $players->perPage() }} @endif z {{ $players->total() }}</span>
                                </div>
                            </div>
                        @endif
                        <button type="button" id="add-player-btn" class="btn btn-outline-success mt-2 mb-4">Dodaj
                            zawodnika
                        </button>
                        <div id="add-player">
                            <h5 class="mt-2 font-weight-bold">Dodaj zawodnika</h5>
                            <hr>
                            <div class="card border-success m-4">
                                <h5 class="card-header">Edytuj dane</h5>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-12">
                                            <form action="{{ route('admin.players.store') }}" method="POST">
                                                @csrf
                                                <div class="form-row ml-2 mr-2">
                                                    <div class="form-group col-md-6">
                                                        <label for="firstName">Imię</label>
                                                        <input type="text" name="first_name"
                                                              value="{{ old('first_name') }}"
                                                              class="form-control @error('first_name') is-invalid @enderror"
                                                              id="firstName" placeholder="Imię" size="50" required>
                                                        @error('first_name')
                                                        <div class="alert alert-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                    <div class="form-group col-md-6">
                                                        <label for="lastName">Nazwisko</label>
                                                        <input type="text" name="last_name"
                                                              value="{{ old('last_name') }}"
                                                              class="form-control @error('last_name') is-invalid @enderror"
                                                              id="lastName" placeholder="Nazwisko" size="50" required>
                                                        @error('last_name')
                                                        <div class="alert alert-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                </div>
                                                <div class="form-row ml-2 mr-2">
                                                    <div class="form-group col-md-6">
                                                        <label for="position">Pozycja</label>
                                                        <select name="position"
                                                                class="form-control @error('position') is-invalid @enderror"
                                                                id="position" required>
                                                            <option selected disabled value="">Wybierz...</option>
                                                            <option value="bramkarz">bramkarz</option>
                                                            <option value="obrońca">obrońca</option>
                                                            <option value="pomocnik">pomocnik</option>
                                                            <option value="napastnik">napastnik</option>
                                                        </select>
                                                        @error('position')
                                                        <div class="alert alert-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                    <div class="form-group col-md-6">
                                                        <label for="number">Numer (opcjonalny)</label>
                                                        <input type="number" name="nr" value="{{ old('nr') }}"
                                                              class="form-control @error('nr') is-invalid @enderror"
                                                              id="number" min="1" step="1" max="99">
                                                        @error('nr')
                                                        <div class="alert alert-danger">{{ $message }}</div>
                                                        @enderror
                                                    </div>
                                                </div>
                                                <button type="submit" class="btn btn-outline-success">Dodaj
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-1 col-lg-2"></div>
                    </div>
                </div>
            </div>
            <!-- /#page-content-wrapper -->
        </div>
        <!-- /#wrapper -->
@endsection