routes/web.php
<?php

use App\Http\Controllers\Main\HomeController;
use App\Http\Controllers\Main\PlayerController;
use App\Http\Controllers\Main\PlayerStatsController;
use App\Http\Controllers\Main\StandingController;
use App\Http\Controllers\Admin\LastMatchController;
use App\Http\Controllers\Admin\UpcomingMatchController;
use App\Http\Controllers\Main\TimetableController;
use App\Http\Controllers\Admin\PlayerController as AdminPlayerController;
use App\Http\Controllers\Admin\StandingController as AdminStandingController;
use App\Http\Controllers\Admin\TimetableController as AdminTimetableController;
use App\Http\Controllers\PageController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UploadController;
use App\Http\Controllers\Main\GalleryController;
use App\Http\Controllers\Admin\GalleryController as AdminGalleryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([], function () {
    Route::get('/', [HomeController::class, 'index'])
        ->name('index');

    Route::get('/gallery', GalleryController::class)
        ->name('gallery');

    Route::group([
        'prefix' => '/season/',
        'as' => 'season.'
    ], function () {
        Route::get('/timetable', [TimetableController::class, 'index'])
            ->name('timetable.index');

        Route::get('/standings', [StandingController::class, 'index'])
            ->name('standings.index');

        Route::get('/players/stats', [PlayerStatsController::class, 'index'])
            ->name('stats.index');

        Route::resource('players', PlayerController::class)
            ->only(['index', 'show'])
            ->where(['player', '[0-9]+']);
    });

    /* AUTH FOR ADMIN ROUTES */
    Route::middleware(['auth'])->group(function () {
        /* ADMIN ROUTES */
        Route::group([
            'prefix' => '/admin',
            'as' => 'admin.'
        ], function () {
            /* DASHBOARD */
            Route::get('/', function () {
                return view('admin.dashboard');
            })->name('dashboard');

            Route::post('/upload', [UploadController::class, 'store']);

            /* TIMETABLE */
            Route::get('/timetable/create', [AdminTimetableController::class, 'create'])
                ->name('timetable.create');

            Route::post('/timetable', [AdminTimetableController::class, 'store'])
                ->name('timetable.store');

            Route::get('/timetable/edit', [AdminTimetableController::class, 'edit'])
                ->name('timetable.edit');

            Route::delete('/timetable', [AdminTimetableController::class, 'destroy'])
                ->name('timetable.destroy');

            Route::delete('/timetable/one/', [AdminTimetableController::class, 'destroyOne'])
                ->name('timetable.destroy.one');


            /* STANDING */
            Route::get('/standing/create', [AdminStandingController::class, 'create'])
                ->name('standing.create');

            Route::post('/standing', [AdminStandingController::class, 'store'])
                ->name('standing.store');

            Route::delete('/standing', [AdminStandingController::class, 'destroy'])
                ->name('standing.destroy');

            /* MATCHES */
            Route::group([
                'prefix' => '/matches/',
                'as' => 'matches.'
            ], function () {
                Route::get('/last/edit', [LastMatchController::class, 'edit'])
                    ->name('last.edit');

                Route::put('/last', [LastMatchController::class, 'update'])
                    ->name('last.update');

                Route::get('/upcoming/edit', [UpcomingMatchController::class, 'edit'])
                    ->name('upcoming.edit');

                Route::put('/upcoming', [UpcomingMatchController::class, 'update'])
                    ->name('upcoming.update');
            });

            /* PLAYERS */
            Route::resource('players', AdminPlayerController::class)
                ->only('index', 'store', 'update', 'edit', 'destroy')
                ->where(['player', '[0-9]+']);

            Route::group([
                'prefix' => '/players',
                'as' => 'players.'
            ], function () {
                Route::put('/{player}/restore', [AdminPlayerController::class, 'restoreDefaults'])
                    ->name('restore')
                    ->where('player', '[0-9]+');

                Route::put('/', [AdminPlayerController::class, 'updatePlayedMatches'])
                    ->name('update.playedMatches');

                Route::delete('/image/{player}', [AdminPlayerController::class, 'destroyImage'])
                    ->name('destroy.image')
                    ->where('player', '[0-9]+');
            });

            /* GALLERY */
            Route::group([
                'prefix' => '/photos',
                'as' => 'photos.'
            ], function () {
                Route::get('/create', [AdminGalleryController::class, 'create'])
                    ->name('create');
                Route::post('/', [AdminGalleryController::class, 'store'])
                    ->name('store');
                Route::delete('/{photo}', [AdminGalleryController::class, 'destroy'])
                    ->name('destroy');
            });
        });
    });

    /* STATIC PAGES */
    Route::get('/{page}', PageController::class)
        ->name('page')
        ->where('page', 'about|contact|privacy-policy');
});

/* AUTH */
Auth::routes();

Auth::routes([
     'register' => false,   // disable registration for new users
     'reset' => false,  // disable password reset
     'verify' => false, // disable email verification
]);

resources/views/shared/footer.blade.php
<div id="footer" class="row mx-auto custom-footer">
    <div class="col-12 col-xl-3 pt-3 pb-3 text-center">
        <div class="container">
            <div class="row">
                <div class="col-4 d-flex">
                    <ul class="list-inline mx-auto justify-content-center site-map-list">
                        <li class="text-center text-uppercase font-weight-bold letter-spacing-1 word-spacing-2">Regulaminy</li>
                    </ul>
                </div>
                <div class="col-4 d-flex">
                    <ul class="list-inline mx-auto justify-content-center site-map-list site-map-list">
                        <li class="text-uppercase font-weight-bold letter-spacing-1 word-spacing-2">Mapa strony</li>
                    </ul>
                </div>
                <div class="col-4 d-flex">
                    <ul class="list-inline mx-auto justify-content-center site-map-list site-map-list">
                        <li class="text-uppercase font-weight-bold letter-spacing-1 word-spacing-2">Inne serwisy</li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-4 d-flex">
                    <ul class="list-inline mx-auto justify-content-center site-map-list site-map-list">
                        <li><a href="{{ route('page', 'privacy-policy') }}" class="font-white">Polityka prywatności</a></li>
                    </ul>
                </div>
                <div class="col-4 d-flex">
                    <ul class="list-inline mx-auto justify-content-center site-map-list site-map-list">
                        <li><a href="{{ route('page', 'about') }}" class="font-white">O klubie</a></li>
                        <li><a href="{{ route('page', 'contact') }}" class="font-white">Kontakt</a></li>
                        <li><a href="{{ route('season.timetable.index') }}" class="font-white">Terminarz</a></li>
                        <li><a href="{{ route('season.standings.index') }}" class="font-white">Tabela</a></li>
                        <li><a href="{{ route('season.players.index') }}" class="font-white">Kadra</a></li>
                        <li><a href="{{ route('season.stats.index') }}" class="font-white">Statystyki</a></li>
                    </ul>
                </div>
                <div class="col-4 d-flex">
                    <ul class="list-inline mx-auto justify-content-center site-map-list site-map-list">
                        <li><a href="http://www.90minut.pl/skarb.php?id_klub=6883&id_sezon=97" target="_blank" class="font-white">90minut.pl</a></li>
                        <li><a href="https://www.laczynaspilka.pl/klub/niebieszczany-remix,6431.html" target="_blank" class="font-white">laczynaspilka.pl</a></li>
                        <li><a href="https://www.ozpnkrosno.pl" target="_blank" class="font-white">OZPN Krosno</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-1">
        <hr class="d-none d-xl-flex vertical-hr">
        <hr class="d-flex d-xl-none horizontal-hr">
    </div>
    <div class="col-12 col-xl-4 pt-3 pb-3 text-center vertical-center">
        <span class="text-uppercase letter-spacing-1 word-spacing-2 font-weight-bold">Odwiedź nas w mediach społecznościowych</span>
        <br>
        <span class="social-icons">
            <a href="https://www.facebook.com/niebieszczany.remix" target="_blank">
                <i class="fab fa-facebook mr-3"></i>
            </a>
            <a href="https://www.instagram.com/rmx1994/" target="_blank">
                <i class="fab fa-instagram"></i>
            </a>
        </span>
        <br>
        <br>
        <span class="text-uppercase letter-spacing-1 word-spacing-2"><i class="fas fa-phone-alt"></i><a href="tel:695780307" target="_blank" class="font-white"> 695-780-307</a></span>
        <br>
        <span class="text-uppercase letter-spacing-1 word-spacing-2"><i class="far fa-envelope-open"></i><a href="mailto:kontakt@remixniebieszczany.pl" target="_blank" class="font-white"> kontakt@remixniebieszczany.pl</a></span>
        <br>
        <span class="text-uppercase letter-spacing-1 word-spacing-2">NIP: 6871791491</span>
        <br>
        <span class="text-uppercase letter-spacing-1 word-spacing-2">REGON: 371011186</span>
    </div>
    <div class="col-xl-1">
        <hr class="d-none d-xl-flex vertical-hr">
        <hr class="d-flex d-xl-none horizontal-hr">
    </div>
    <div class="col-12 col-xl-3 pt-3 pb-3 text-center vertical-center">
        <span class="text-uppercase letter-spacing-1 word-spacing-2">Wszelkie prawa zastrzeżone</span>
        <br>
        <span class="text-uppercase letter-spacing-1 word-spacing-2">&copy<script>document.write(new Date().getFullYear().toString());</script> Remix Niebieszczany</span>
        <br><br>
        <span class="text-uppercase letter-spacing-1 word-spacing-2">Stronę wykonał Jakub Pałys</span>
    </div>
</div>

resources/views/shared/header.blade.php
<div id="header" class="row mx-auto pt-3 pb-3">
    <div class="col-12 col-lg-2 d-flex align-items-center justify-content-center">
        <a href="{{ route('index') }}">
            <img src="{{ url('/assets/remix-logo.png') }}" alt="Logo Remix Niebieszczany">
        </a>
    </div>
    <div class="col-12 col-lg-8 d-flex align-items-center justify-content-center text-center text-uppercase title">LKS Remix Niebieszczany</div>
    <div class="col-12 col-lg-2 d-flex align-items-center justify-content-end">
        <div class="share-button d-none d-xl-flex">
            <span>Polub nas</span>
            <a href="https://www.facebook.com/niebieszczany.remix" target="_blank"><i class="fab fa-facebook-f"></i></a>
            <a href="https://www.instagram.com/rmx1994/" target="_blank"><i class="fab fa-instagram"></i></a>
        </div>
    </div>
</div>
<nav id="navbar_top" class="navbar navbar-expand-xl navbar-custom shadow-lg">
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
            <i class="fas fa-bars"></i>
        </span>
    </button>
    <div class="collapse navbar-collapse ml-xl-5 pl-xl-5" id="navbarNav">
        <ul class="navbar-nav mx-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('index') }}"><i class="fas fa-home mr-3"></i>Strona główna</a>
            </li>
            <li class="nav-item dropdown ml-3">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-male mr-3"></i>Sezon</a>
                <div class="dropdown-menu shadow p-3 mb-5 bg-white rounded" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{{ route('season.timetable.index') }}">Terminarz</a>
                    <a class="dropdown-item" href="{{ route('season.standings.index') }}">Tabela</a>
                    <a class="dropdown-item" href="{{ route('season.players.index') }}">Kadra</a>
                    <a class="dropdown-item" href="{{ route('season.stats.index') }}">Statystyki</a>
                </div>
            <li class="nav-item ml-3">
                <a class="nav-link" href="{{ route('gallery') }}"><i class="fas fa-images mr-3"></i>Galeria</a>
            </li>
            <li class="nav-item ml-3">
                <a class="nav-link" href="{{ route('page', 'about') }}"><i class="fas fa-info-circle mr-3"></i>O klubie</a>
            </li>
            <li class="nav-item ml-3">
                <a class="nav-link" href="{{ route('page', 'contact') }}"><i class="far fa-address-book mr-3"></i>Kontakt</a>
            </li>
            @auth
                <li class="nav-item ml-3">
                    <a class="nav-link" href="{{ route('admin.dashboard') }}"><i class="far fa-address-book mr-3"></i>Panel administratora</a>
                </li>
            @endauth
            <li>
                <hr class="d-flex d-xl-none horizontal-hr">
            </li>
            <li class="row">
                <div class="col-6 d-flex d-xl-none justify-content-start mt-3 mb-2">
                    @guest
                    <a href="{{ route('login') }}" class="vertical-btn">
                        <span class="text">Logowanie</span>
                    </a>
                    @endguest
                </div>
                <div class="col-6 d-flex d-xl-none justify-content-end mt-3 mb-2">
                    <div class="share-button-mobile d-flex d-xl-none">
                        <span>Polub nas</span>
                        <a href="https://www.facebook.com/niebieszczany.remix"><i class="fab fa-facebook-f"></i></a>
                        <a href="https://www.instagram.com/rmx1994/"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
        <div class="d-none d-xl-flex align-items-center">
            @guest
            <a href="{{ route('login') }}" class="vertical-btn ml-5">
                <span class="text">Logowanie</span>
            </a>
            @endguest
        </div>
</nav>

resources/views/shared/messages.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-block text-center mt-3 mb-3 ml-5 mr-5">
        <i class="fas fa-check mr-5 font-message-icon"></i>
        <button type="button" class="close" data-dismiss="alert">✕</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block text-center mt-3 mb-3 ml-5 mr-5">
        <i class="fas fa-times mr-5 font-message-icon"></i>
        <button type="button" class="close" data-dismiss="alert">✕</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-block text-center mt-3 mb-3 ml-5 mr-5">
        <i class="fas fa-exclamation mr-5 font-message-icon"></i>
        <button type="button" class="close" data-dismiss="alert">✕</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('info'))
    <div class="alert alert-info alert-block text-center mt-3 mb-3 ml-5 mr-5">
        <i class="fas fa-info mr-5 font-message-icon"></i>
        <button type="button" class="close" data-dismiss="alert">✕</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

resources/views/shared/sidebar-admin.blade.php
<!-- Sidebar -->
<div class="bg-light border-right" id="sidebar-wrapper">
    <div class="sidebar-heading font-weight-bold">Menu</div>
    <div class="list-group list-group-flush">
        <a href="{{route('admin.dashboard')}}" class="list-group-item list-group-item-action bg-light sidebar-icon"><i class="fas fa-home"></i> Dashboard</a>
        @can('moderator-level')
            <a href="#" class="list-group-item list-group-item-action bg-light disabled font-weight-bold text-uppercase sidebar-icon">Terminarz</a>
            <a href="{{route('admin.timetable.create')}}" class="list-group-item list-group-item-action bg-light pl-5 sidebar-icon"><i class="far fa-calendar-plus"></i> Dodaj kolejkę</a>
            <a href="{{route('admin.timetable.edit')}}" class="list-group-item list-group-item-action bg-light pl-5 sidebar-icon"><i class="far fa-calendar-minus"></i> Usuń kolejkę</a>
            <a href="#" class="list-group-item list-group-item-action bg-light disabled font-weight-bold text-uppercase sidebar-icon">Mecze</a>
            <a href="{{route('admin.matches.last.edit')}}" class="list-group-item list-group-item-action bg-light pl-5 sidebar-icon"><i class="fas fa-backward"></i> Ostatni mecz</a>
            <a href="{{route('admin.matches.upcoming.edit')}}" class="list-group-item list-group-item-action bg-light pl-5 sidebar-icon"><i class="fas fa-forward"></i> Najbliższy mecz</a>
            <a href="{{route('admin.standing.create')}}" class="list-group-item list-group-item-action bg-light sidebar-icon"><i class="fas fa-table"></i> Tabela</a>
            <a href="{{route('admin.players.index')}}" class="list-group-item list-group-item-action bg-light sidebar-icon"><i class="fas fa-list"></i> Lista zawodników</a>
            <a href="{{route('admin.photos.create')}}" class="list-group-item list-group-item-action bg-light sidebar-icon"><i class="fas fa-images"></i> Galeria</a>
        @endcan
        <form method="POST" action="{{ route('logout') }}">
            @csrf
            <button type="submit" class="list-group-item-logout list-group-item-action bg-light sidebar-icon"><i class="fas fa-sign-out-alt"></i> Wyloguj</button>
        </form>
    </div>
</div>
<!-- /#sidebar-wrapper -->