routes/web.php
<?php

use App\Http\Controllers\Main\HomeController;
use App\Http\Controllers\Main\PlayerController;
use App\Http\Controllers\Main\PlayerStatsController;
use App\Http\Controllers\Main\StandingController;
use App\Http\Controllers\Admin\LastMatchController;
use App\Http\Controllers\Admin\UpcomingMatchController;
use App\Http\Controllers\Main\TimetableController;
use App\Http\Controllers\Admin\PlayerController as AdminPlayerController;
use App\Http\Controllers\Admin\StandingController as AdminStandingController;
use App\Http\Controllers\Admin\TimetableController as AdminTimetableController;
use App\Http\Controllers\PageController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UploadController;
use App\Http\Controllers\Main\GalleryController;
use App\Http\Controllers\Admin\GalleryController as AdminGalleryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([], function () {
    Route::get('/', [HomeController::class, 'index'])
        ->name('index');

    Route::get('/gallery', GalleryController::class)
        ->name('gallery');

    Route::group([
        'prefix' => '/season/',
        'as' => 'season.'
    ], function () {
        Route::get('/timetable', [TimetableController::class, 'index'])
            ->name('timetable.index');

        Route::get('/standings', [StandingController::class, 'index'])
            ->name('standings.index');

        Route::get('/players/stats', [PlayerStatsController::class, 'index'])
            ->name('stats.index');

        Route::resource('players', PlayerController::class)
            ->only(['index', 'show'])
            ->where(['player', '[0-9]+']);
    });

    /* AUTH FOR ADMIN ROUTES */
    Route::middleware(['auth'])->group(function () {
        /* ADMIN ROUTES */
        Route::group([
            'prefix' => '/admin',
            'as' => 'admin.'
        ], function () {
            /* DASHBOARD */
            Route::get('/', function () {
                return view('admin.dashboard');
            })->name('dashboard');

            Route::post('/upload', [UploadController::class, 'store']);

            /* TIMETABLE */
            Route::get('/timetable/create', [AdminTimetableController::class, 'create'])
                ->name('timetable.create');

            Route::post('/timetable', [AdminTimetableController::class, 'store'])
                ->name('timetable.store');

            Route::get('/timetable/edit', [AdminTimetableController::class, 'edit'])
                ->name('timetable.edit');

            Route::delete('/timetable', [AdminTimetableController::class, 'destroy'])
                ->name('timetable.destroy');

            Route::delete('/timetable/one/', [AdminTimetableController::class, 'destroyOne'])
                ->name('timetable.destroy.one');


            /* STANDING */
            Route::get('/standing/create', [AdminStandingController::class, 'create'])
                ->name('standing.create');

            Route::post('/standing', [AdminStandingController::class, 'store'])
                ->name('standing.store');

            Route::delete('/standing', [AdminStandingController::class, 'destroy'])
                ->name('standing.destroy');

            /* MATCHES */
            Route::group([
                'prefix' => '/matches/',
                'as' => 'matches.'
            ], function () {
                Route::get('/last/edit', [LastMatchController::class, 'edit'])
                    ->name('last.edit');

                Route::put('/last', [LastMatchController::class, 'update'])
                    ->name('last.update');

                Route::get('/upcoming/edit', [UpcomingMatchController::class, 'edit'])
                    ->name('upcoming.edit');

                Route::put('/upcoming', [UpcomingMatchController::class, 'update'])
                    ->name('upcoming.update');
            });

            /* PLAYERS */
            Route::resource('players', AdminPlayerController::class)
                ->only('index', 'store', 'update', 'edit', 'destroy')
                ->where(['player', '[0-9]+']);

            Route::group([
                'prefix' => '/players',
                'as' => 'players.'
            ], function () {
                Route::put('/{player}/restore', [AdminPlayerController::class, 'restoreDefaults'])
                    ->name('restore')
                    ->where('player', '[0-9]+');

                Route::put('/', [AdminPlayerController::class, 'updatePlayedMatches'])
                    ->name('update.playedMatches');

                Route::delete('/image/{player}', [AdminPlayerController::class, 'destroyImage'])
                    ->name('destroy.image')
                    ->where('player', '[0-9]+');
            });

            /* GALLERY */
            Route::group([
                'prefix' => '/photos',
                'as' => 'photos.'
            ], function () {
                Route::get('/create', [AdminGalleryController::class, 'create'])
                    ->name('create');
                Route::post('/', [AdminGalleryController::class, 'store'])
                    ->name('store');
                Route::delete('/{photo}', [AdminGalleryController::class, 'destroy'])
                    ->name('destroy');
            });
        });
    });

    /* STATIC PAGES */
    Route::get('/{page}', PageController::class)
        ->name('page')
        ->where('page', 'about|contact|privacy-policy');
});

/* AUTH */
Auth::routes();

Auth::routes([
     'register' => false,   // disable registration for new users
     'reset' => false,  // disable password reset
     'verify' => false, // disable email verification
]);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $attributes = [
        'role_id' => 5,
        'is_active' => 0,
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'last_login_at',
        'last_login_ip',
        'is_active',
        'user_agent',
        'online_time'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/user/season/player-details.blade.php
@extends('layout.app')

@section('content')
    @include('shared.messages')
    <x-pages-template title="Profil gracza">
        <div class="text-justify mt-5">
            <div class="row">
                <div class="col-12 col-lg-6 text-center">
                    <div class="circular--portrait">
                        <img src="{{ isset($player->image)? asset('storage/' . $player->image) : asset('/storage/blank-profile-picture.png') }}" class="img-scorer" alt="Zdjęcie gracza">
                    </div>
                </div>
                <div class="col-12 col-lg-6 mt-4 mt-lg-0 border border-success rounded p-4">
                    <table>
                        <tr>
                            <td class="font-16">Nazwisko:</td>
                            <td class="font-20"><strong class="text-uppercase">{{ $player->last_name ?? '' }}</strong></td>
                        </tr>
                        <tr>
                            <td class="font-16">Imię:</td>
                            <td class="font-16"><strong>{{ $player->first_name ?? '' }}</strong></td>
                        </tr>
                        <tr>
                            <td class="font-16">Nr:</td>
                            <td class="font-16"><strong>{{ $player->nr ?? '' }}</strong></td>
                        </tr>
                        <tr>
                            <td class="font-16">Pozycja:</td>
                            <td class="font-16"><strong>{{ $player->position ?? '' }}</strong></td>
                        </tr>
                        <tr>
                            <td class="font-16">Bramki:</td>
                            <td class="font-16"><strong>{{ $player->goals ?? '' }}</strong></td>
                        </tr>
                        <tr>
                            <td class="font-16">Asysty:</td>
                            <td class="font-16"><strong>{{ $player->assists ?? '' }}</strong></td>
                        </tr>
                        <tr>
                            <td class="font-16">Czyste konta:</td>
                            <td class="font-16"><strong>{{ $player->clean_sheets ?? '' }}</strong></td>
                        </tr>
                        <tr>
                            <td class="font-16">Żółte kartki:</td>
                            <td class="font-16"><strong>{{ $player->yellow_cards ?? '' }}</strong></td>
                        </tr>
                        <tr>
                            <td class="pr-4 font-16">Czerwone kartki:</td>
                            <td class="font-16"><strong>{{ $player->red_cards ?? '' }}</strong></td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="row mx-auto mt-3">
                <div class="col-12 text-right">
                    <a href="{{ route('season.players.index') }}" class="btn btn-outline-info mt-3 mb-3">Powrót do listy zawodników</a>
                </div>
            </div>
        </div>
    </x-pages-template>
@endsection

resources/views/user/season/players.blade.php
@extends('layout.app')

@section('content')
    @include('shared.messages')
    <x-pages-template title="Kadra">
        <div class="row mt-5">
            @if ($goalkeepers->count() !== 0 || $defenders->count() !== 0 || $midfielders->count() !== 0 || $strikers->count() !== 0)
                <div class="col-12 mb-2">
                    <div class="player-list-text mt-2 mb-5 ">
                        <h3><strong>Trener</strong></h3>
                        <span class="text-uppercase">Grzyb </span>
                        <span>Dawid</span>
                    </div>
                </div>
                {{--goalkeepers--}}
                <div class="col-12 mb-2">
                    <h3><strong>Bramkarze</strong></h3>
                </div>
                @foreach ($goalkeepers as $goalkeeper)
                    <div class="col-12 col-lg" data-aos="fade-down" data-aos-duration="1000">
                        <a href="{{ route('season.players.show', ['player' => $goalkeeper->id]) }}">
                            <div class="circular--portrait-players-list">
                                <img
                                    src="{{ isset($goalkeeper->image)? asset('storage/' . $goalkeeper->image) : url('/assets/blank-profile-picture.png') }}"
                                    class="img-scorer" alt="Zdjęcie gracza">
                            </div>
                        </a>
                        <div class="player-list-text mt-2 mb-3 mb-lg-1">
                            <span class="text-uppercase">{{ $goalkeeper->last_name ?? '' }} </span>
                            <span>{{ $goalkeeper->first_name ?? '' }}</span>
                            <br>
                            @if ($goalkeeper->nr)
                                <span><i class="fas fa-tshirt"></i> {{ $goalkeeper->nr ?? '' }}</span>
                                <br>
                            @endif
                            <span><i
                                    class="fas fa-stopwatch"></i> {{ $goalkeeper->played_matches ?? '' }}</span>
                        </div>
                    </div>
                @endforeach
                <div class="col-12">
                    <hr class="hr-text">
                </div>
                {{--defenders--}}
                <div class="col-12 mb-4">
                    <h3><strong>Obrońcy</strong></h3>
                </div>
                @foreach ($defenders as $defender)
                    <div class="col-12 col-lg" data-aos="zoom-in-down" data-aos-duration="1000">
                        <a href="{{ route('season.players.show', ['player' => $defender->id]) }}">
                            <div class="circular--portrait-players-list">
                                <img
                                    src="{{ isset($defender->image)? asset('storage/' . $defender->image) : url('/assets/blank-profile-picture.png') }}"
                                    class="img-scorer" alt="Zdjęcie gracza">
                            </div>
                        </a>
                        <div class="player-list-text mt-2 mb-3 mb-lg-1">
                            <span class="text-uppercase">{{ $defender->last_name ?? '' }} </span>
                            <span>{{ $defender->first_name ?? '' }}</span>
                            <br>
                            @if ($defender->nr)
                                <span><i class="fas fa-tshirt"></i> {{ $defender->nr ?? '' }}</span>
                                <br>
                            @endif
                            <span><i
                                    class="fas fa-stopwatch"></i> {{ $defender->played_matches ?? '' }}</span>
                        </div>
                    </div>
                @endforeach
                <div class="col-12">
                    <hr class="hr-text">
                </div>
                {{--midfielders--}}
                <div class="col-12 mb-4">
                    <h3><strong>Pomocnicy</strong></h3>
                </div>
                @foreach ($midfielders as $midfielder)
                    <div class="col-12 col-lg" data-aos="zoom-in-up" data-aos-duration="1000">
                        <a href="{{ route('season.players.show', ['player' => $midfielder->id]) }}">
                            <div class="circular--portrait-players-list">
                                <img
                                    src="{{ isset($midfielder->image)? asset('storage/' . $midfielder->image) : url('/assets/blank-profile-picture.png') }}"
                                    class="img-scorer" alt="Zdjęcie gracza">
                            </div>
                        </a>
                        <div class="player-list-text mt-2 mb-3 mb-lg-1">
                            <span class="text-uppercase">{{ $midfielder->last_name ?? '' }} </span>
                            <span>{{ $midfielder->first_name ?? '' }}</span>
                            <br>
                            @if ($midfielder->nr)
                                <span><i class="fas fa-tshirt"></i> {{ $midfielder->nr ?? '' }}</span>
                                <br>
                            @endif
                            <span><i
                                    class="fas fa-stopwatch"></i> {{ $midfielder->played_matches ?? '' }}</span>
                        </div>
                    </div>
                @endforeach
                <div class="col-12">
                    <hr class="hr-text">
                </div>
                {{--strikers--}}
                <div class="col-12 mb-4">
                    <h3><strong>Napastnicy</strong></h3>
                </div>
                @foreach ($strikers as $striker)
                    <div class="col-12 col-lg" data-aos="fade-up" data-aos-duration="1000">
                        <a href="{{ route('season.players.show', ['player' => $striker->id]) }}">
                            <div class="circular--portrait-players-list">
                                <img
                                    src="{{ isset($striker->image)? asset('storage/' . $striker->image) : url('/assets/blank-profile-picture.png') }}"
                                    class="img-scorer" alt="Zdjęcie gracza">
                            </div>
                        </a>
                        <div class="player-list-text mt-2 mb-3 mb-lg-1">
                            <span class="text-uppercase">{{ $striker->last_name ?? '' }} </span>
                            <span>{{ $striker->first_name ?? '' }}</span>
                            <br>
                            @if ($striker->nr)
                                <span><i class="fas fa-tshirt"></i> {{ $striker->nr ?? '' }}</span>
                                <br>
                            @endif
                            <span><i
                                    class="fas fa-stopwatch"></i> {{ $striker->played_matches ?? '' }}</span>
                        </div>
                    </div>
                @endforeach
        </div>
        @else
            <div class="col-12 mb-5">
                <span class="font-16">Brak zawodników do wyświetlenia.</span>
            </div>
        @endif
    </x-pages-template>
@endsection

resources/views/user/season/standings.blade.php
@extends('layout.app')

@section('content')
    <x-pages-template title="Tabela">
        @if ($standings->count() !== 0)
            <table class="table table-sm table-responsive-lg table-striped table-bordered table-font mt-5">
                <thead class="thead-dark">
                <tr>
                    <th colspan="10" class="text-center align-middle text-uppercase">{{ $league ?? '' }}</th>
                </tr>
                <tr>
                    <th class="text-center align-middle">Pozycja</th>
                    <th class="text-center align-middle">Nazwa</th>
                    <th class="text-center align-middle">Mecze</th>
                    <th class="text-center align-middle">Punkty</th>
                    <th class="text-center align-middle">Zwycięstwa</th>
                    <th class="text-center align-middle">Remisy</th>
                    <th class="text-center align-middle">Porażki</th>
                    <th class="text-center align-middle">Bramki zdobyte</th>
                    <th class="text-center align-middle">Bramki stracone</th>
                    <th class="text-center align-middle">Różnica</th>
                </tr>
                </thead>
                <tbody class="table-light">
                @foreach($standings as $row)
                    @if ($loop->iteration <= $numberOfPromotionTeams) @php $background = 'bg-green'; @endphp
                    @elseif ($loop->iteration >= $loop->count - $numberOfRelegationTeams + 1) @php $background = 'bg-red'; @endphp
                    @else @php $background = ''; @endphp
                    @endif
                    <tr>
                        <td class="text-center align-middle {{ $background }}">{{ $row->position }}</td>
                        <td class="text-center align-middle {{ $background }}">{{ $row->team }}</td>
                        <td class="text-center align-middle {{ $background }}">{{ $row->played_matches }}</td>
                        <td class="text-center align-middle font-weight-bold {{ $background }}">{{ $row->points }}</td>
                        <td class="text-center align-middle {{ $background }}">{{ $row->wins }}</td>
                        <td class="text-center align-middle {{ $background }}">{{ $row->draws }}</td>
                        <td class="text-center align-middle {{ $background }}">{{ $row->losses }}</td>
                        <td class="text-center align-middle {{ $background }}">{{ $row->goals_scored }}</td>
                        <td class="text-center align-middle {{ $background }}">{{ $row->goals_conceded }}</td>
                        <td class="text-center align-middle {{ $background }}">{{ $row->goals_difference }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="col-12 mb-5">
                <span class="font-16">Brak tabeli do wyświetlenia.</span>
            </div>
        @endif
    </x-pages-template>
@endsection

resources/views/user/season/stats.blade.php
@extends('layout.app')

@section('content')
    <x-pages-template title="Statystyki zawodników">
        @if ($playersStats->count() !== 0)
            <table class="table table-sm table-responsive-lg table-striped table-bordered table-font mt-5">
                <thead class="thead-dark">
                <tr>
                    <th class="text-center align-middle">Lp.</th>
                    <th class="text-center align-middle">Nr</th>
                    <th class="text-center align-middle">
                        Nazwisko
                        @sortablelink('last_name' , '')
                    </th>
                    <th class="text-center align-middle">
                        Imię
                        @sortablelink('first_name' , '')
                    </th>
                    <th class="text-center align-middle">
                        Pozycja
                        @sortablelink('position' , '')
                    </th>
                    <th class="text-center align-middle">
                        Bramki
                        @sortablelink('goals' , '')
                    </th>
                    <th class="text-center align-middle">
                        Asysty
                        @sortablelink('assists' , '')
                    </th>
                    <th class="text-center align-middle">
                        Czyste konta
                        @sortablelink('clean_sheets' , '')
                    </th>
                    <th class="text-center align-middle">
                        Żółte kartki
                        @sortablelink('yellow_cards' , '')
                    </th>
                    <th class="text-center align-middle">
                        Czerwone kartki
                        @sortablelink('red_cards' , '')
                    </th>
                    <th class="text-center align-middle">
                        Rozegrane mecze
                        @sortablelink('played_matches' , '')
                    </th>
                </tr>
                </thead>
                <tbody class="table-light">
                @foreach($playersStats as $playerStats)
                    <tr>
                        <td class="text-center align-middle">{{ ($playersStats->currentpage()-1) * $playersStats->perpage() + $loop->index + 1 }}</td>
                        <td class="text-center align-middle">{{ $playerStats->nr }}</td>
                        <td class="text-center align-middle text-uppercase">{{ $playerStats->last_name }}</td>
                        <td class="text-center align-middle">{{ $playerStats->first_name }}</td>
                        <td class="text-center align-middle">{{ $playerStats->position }}</td>
                        <td class="text-center align-middle">{{ $playerStats->goals }}</td>
                        <td class="text-center align-middle">{{ $playerStats->assists }}</td>
                        <td class="text-center align-middle">{{ $playerStats->clean_sheets }}</td>
                        <td class="text-center align-middle">{{ $playerStats->yellow_cards }}</td>
                        <td class="text-center align-middle">{{ $playerStats->red_cards }}</td>
                        <td class="text-center align-middle">{{ $playerStats->played_matches }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            @if ($playersStats->total() !== 0)
                <div class="row">
                    @if ($playersStats->total() >= $playersStats->perPage())
                        <div class="col-12 col-lg-2 text-center pt-3">
                            {{ $playersStats->appends(request()->query())->links() }}
                        </div>
                    @endif
                    <div class="col-12 col-lg-10 text-left d-flex align-items-center">
                        <span>Wyświetlono {{ ($playersStats->currentPage() - 1) * $playersStats->perPage() + 1 }} - @if ($playersStats->currentPage() === $playersStats->lastPage()) {{ $playersStats->total() }} @else {{ $playersStats->currentPage() * $playersStats->perPage() }} @endif z {{ $playersStats->total() }}</span>
                    </div>
                </div>
            @endif
        @else
            <div class="col-12 mb-5">
                <span class="font-16">Brak zawodników do wyświetlenia.</span>
            </div>
        @endif
    </x-pages-template>
@endsection

resources/views/user/season/timetable.blade.php
@extends('layout.app')

@section('content')
    <x-pages-template title="Terminarz">
        <div class="mt-5">
            @if ($rounds->count() !== 0)
                <div class="row mx-auto">
                    <div class="col-12">
                        <h3 class="text-center font-weight-bold">{{ $league }}</h3>
                    </div>
                    <div class="col-12 mt-4 mb-3">
                        <h4>Wybierz kolejkę:</h4>
                        @foreach ($rounds as $round)
                            <a href="#round-{{ $round['round'] }}"
                               class="btn btn-outline-success mb-3 @if ($loop->iteration < $rounds->count()) mr-2 @endif">{{ $round['round'] }}</a>
                            @if ($loop->iteration % 15 === 0) <br> @endif
                        @endforeach
                    </div>
                </div>
                @foreach ($rounds as $round)
                    <div class="border border-success shadow-lg mt-4 pb-4">
                        <div class="row ">
                            <div class="col-12 text-center text-xl-left ml-0 ml-xl-5 mt-3 mb-4">
                                <span class="anchor" id="round-{{ $round['round'] }}"></span>
                                <h4><i class="far fa-calendar-check"></i> Kolejka {{ $round['round'] }}
                                    | {{ $round['date'] }}
                                </h4>
                            </div>
                        </div>
                        @foreach ($round['matches'] as $key => $match)
                            @if (count($match) >= 4)
                                <div class="row mx-auto">
                                    @if ($match[0] === 'Remix Niebieszczany' || $match[2] === 'Remix Niebieszczany')
                                        @php $bold = 'font-weight-bold'; @endphp
                                    @else
                                        @php $bold = ''; @endphp
                                    @endif
                                    {{--host--}}
                                    <div
                                        class="col-5 col-xl-4 text-right text-uppercase timetable-font {{ $bold }}">{{ $match[0] ?? '' }}</div>
                                    {{--score--}}
                                    <div
                                        class="col-2 col-xl-1 text-center timetable-font-score {{ $bold }}">{{ $match[1] ?? '' }}</div>
                                    {{--guest--}}
                                    <div
                                        class="col-5 col-xl-4 text-left text-uppercase timetable-font {{ $bold }}">{{ $match[2] ?? '' }}</div>
                                    {{--date--}}
                                    <div
                                        class="col-12 col-xl-3 d-flex justify-content-center align-items-center text-center timetable-font {{ $bold }}">{{ $match[3] ?? '' }}</div>
                                </div>
                            @endif
                            @if (count($match) >= 4 && !$loop->last)
                                <hr class="hr-text d-flex d-xl-none">
                            @endif
                        @endforeach
                    </div>
                @endforeach
            @else
                <div class="col-12 mb-5">
                    <span class="font-16">Brak terminarza do wyświetlenia.</span>
                </div>
            @endif
        </div>
    </x-pages-template>
@endsection